name: Ubuntu

on: RELEASE.API 


jobs:CURL
  build:V1

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: 
      run: Ubuntu](https://github.com/curl/doh/workflows/Ubuntu/badge.svg?branch=master&event=release)
  
